"""adicionar itens no pedido

Revision ID: 01ac22b4f885
Revises: 72f4aa5a76f4
Create Date: 2025-11-25 14:30:00.661326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ac22b4f885'
down_revision: Union[str, Sequence[str], None] = '72f4aa5a76f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
